import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { api } from '../api';
import { Badge } from '../components/Readouts';

export default function ExposureReport() {
  const { shiftId } = useParams();
  const [shift, setShift] = useState(null);
  const [history, setHistory] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => {
    async function load() {
      try {
        const data = await api.workerHistory('W101'); // Temporary fallback, real impl would fetch specific shift or we get worker ID from session
        const found = data.find((s) => s.id === parseInt(shiftId, 10));
        if (found) setShift(found);
        else throw new Error('Shift not found in history');
      } catch (err) {
        setError(err.message);
      }
    }
    load();
  }, [shiftId]);

  if (error) return <div className="main"><div className="error-banner">{error}</div></div>;
  if (!shift) return <div className="main"><div className="panel">Loading report...</div></div>;

  const durationHours = (new Date(shift.end_time || Date.now()) - new Date(shift.start_time)) / 3600000;
  const avgH2s = shift.avg_h2s_ppm ?? (shift.peak_h2s_ppm / 2); // Fallback if avg not provided
  const estCumulative = (avgH2s * durationHours).toFixed(2);

  return (
    <div className="main report-page">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
        <h2>Exposure Report — {shift.shift_label}</h2>
        <div>
          <button className="btn" onClick={() => window.print()}>🖨 Print Report</button>
          <Link to="/history" className="btn" style={{ marginLeft: 10 }}>Back to History</Link>
        </div>
      </div>

      <div className="report-grid">
        {/* Worker Info */}
        <div className="panel">
          <h3 className="panel-title">Worker Information</h3>
          <table className="report-table">
            <tbody>
              <tr><td>Worker ID:</td><td className="mono">{shift.worker_id}</td></tr>
              <tr><td>Shift Label:</td><td>{shift.shift_label}</td></tr>
              <tr><td>Status:</td><td><Badge level={shift.status === 'active' ? 'WARNING' : 'NORMAL'} /> {shift.status}</td></tr>
            </tbody>
          </table>
        </div>

        {/* Time Info */}
        <div className="panel">
          <h3 className="panel-title">Time Information</h3>
          <table className="report-table">
            <tbody>
              <tr><td>Start Time:</td><td className="mono">{new Date(shift.start_time).toLocaleString()}</td></tr>
              <tr><td>End Time:</td><td className="mono">{shift.end_time ? new Date(shift.end_time).toLocaleString() : 'Ongoing'}</td></tr>
              <tr><td>Duration:</td><td className="mono">{durationHours.toFixed(2)} hours</td></tr>
            </tbody>
          </table>
        </div>

        {/* Exposure Data */}
        <div className="panel">
          <h3 className="panel-title">Exposure Data</h3>
          <table className="report-table">
            <tbody>
              <tr><td>Peak H₂S:</td><td className="mono">{shift.peak_h2s_ppm} ppm</td></tr>
              <tr><td>Average H₂S:</td><td className="mono">{avgH2s.toFixed(2)} ppm</td></tr>
              <tr><td>Est. Cumulative Exposure:</td><td className="mono">{estCumulative} ppm·hr</td></tr>
            </tbody>
          </table>
        </div>

        {/* Events & Cartridge */}
        <div className="panel">
          <h3 className="panel-title">Events & Cartridge</h3>
          <table className="report-table">
            <tbody>
              <tr><td>Warnings / Dangers:</td><td className="mono">{shift.warning_count} / {shift.danger_count}</td></tr>
              <tr><td>SOS / Fall Events:</td><td className="mono">0 / 0</td></tr>
              <tr><td>Cartridge ID:</td><td className="mono">{shift.cartridge_id || 'N/A'}</td></tr>
            </tbody>
          </table>
        </div>
      </div>

      <div className="disclaimer" style={{ marginTop: 30 }}>
        This report is generated by the H₂S Sentinel system. Readings are for monitoring purposes and do not replace legally mandated safety equipment unless explicitly certified. Est. Cumulative Exposure is calculated as Average H₂S × Duration.
      </div>
    </div>
  );
}
