import { useState, useEffect, useRef, useCallback } from 'react';
import { useAuth } from '../context/AuthContext';
import { useSimulation } from '../context/SimulationContext';
import { api } from '../api';
import { Readout, Badge, AlertFeed } from '../components/Readouts';
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, ReferenceLine,
} from 'recharts';

function riskFromPpm(ppm) {
  if (ppm == null) return 'UNKNOWN';
  if (ppm >= 50) return 'EMERGENCY';
  if (ppm >= 20) return 'DANGER';
  if (ppm >= 10) return 'WARNING';
  return 'NORMAL';
}

function motionLabel(state) {
  if (state === 'fall_suspected') return 'FALL DETECTED';
  if (state === 'inactive') return 'INACTIVE';
  return 'Active';
}

function motionRisk(state) {
  if (state === 'fall_suspected') return 'DANGER';
  if (state === 'inactive') return 'WARNING';
  return 'NORMAL';
}

export default function WorkerDashboard() {
  const { session } = useAuth();
  const { sim, setH2sLevel, setMotionState, fireSOS, clearSOS, generateReading } = useSimulation();
  const [shift, setShift] = useState(() => {
    const raw = localStorage.getItem('h2s_active_shift');
    return raw ? JSON.parse(raw) : null;
  });
  const [cartridgeId, setCartridgeId] = useState('H2S-CART-001');
  const [shiftLabel, setShiftLabel] = useState('Morning Shift');
  const [latest, setLatest] = useState(null);
  const [alerts, setAlerts] = useState([]);
  const [chartData, setChartData] = useState([]);
  const [cumulativeExposure, setCumulativeExposure] = useState(0);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const tickRef = useRef(0);
  const cumulativeRef = useRef(0);

  const refresh = useCallback(async (shiftId) => {
    try {
      const [l, a] = await Promise.all([
        api.latestReading(shiftId).catch(() => null),
        api.shiftAlerts(shiftId),
      ]);
      if (l) setLatest(l);
      setAlerts(a);
    } catch (err) {
      setError(err.message);
    }
  }, []);

  useEffect(() => {
    if (!shift) return;
    const interval = setInterval(async () => {
      try {
        const reading = generateReading(tickRef.current++);

        // Accumulate estimated cumulative exposure (ppm × hours per tick)
        const tickHours = 3 / 3600; // 3-second interval
        cumulativeRef.current += reading.h2s_ppm * tickHours;
        setCumulativeExposure(Math.round(cumulativeRef.current * 100) / 100);

        await api.sendReading(shift.id, reading);

        // Handle SOS trigger from simulation controls
        if (sim.triggerSOS) {
          await api.sos(shift.id);
          clearSOS();
        }

        await refresh(shift.id);

        // Update chart data (keep last 40 points)
        setChartData((prev) => {
          const next = [
            ...prev,
            {
              time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
              h2s: reading.h2s_ppm,
              hr: reading.hr_bpm,
              spo2: reading.spo2_pct,
            },
          ];
          return next.length > 40 ? next.slice(-40) : next;
        });
      } catch (err) {
        setError(err.message);
      }
    }, 3000);
    refresh(shift.id);
    return () => clearInterval(interval);
  }, [shift, refresh, generateReading, sim.triggerSOS, clearSOS]);

  async function handleStart(e) {
    e.preventDefault();
    setError('');
    setBusy(true);
    try {
      const s = await api.startShift(session.workerId, cartridgeId.trim(), shiftLabel);
      localStorage.setItem('h2s_active_shift', JSON.stringify(s));
      setShift(s);
      tickRef.current = 0;
      cumulativeRef.current = 0;
      setCumulativeExposure(0);
      setChartData([]);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  async function handleEnd() {
    setBusy(true);
    try {
      await api.endShift(shift.id);
      localStorage.removeItem('h2s_active_shift');
      setShift(null);
      setLatest(null);
      setAlerts([]);
      setChartData([]);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  async function handleSOS() {
    if (!shift) return;
    try {
      await api.sos(shift.id);
      await refresh(shift.id);
    } catch (err) {
      setError(err.message);
    }
  }

  const risk = riskFromPpm(latest?.h2s_ppm);
  const motionSt = latest?.motion_state || 'normal';

  return (
    <div className="main">
      {/* SIMULATION MODE banner */}
      <div className="sim-banner">
        <span className="sim-banner-dot" />
        SIMULATION MODE — Sensor data is generated by the browser for prototype demonstration.
        Hardware not connected.
      </div>

      {error && <div className="error-banner">{error}</div>}

      {!shift ? (
        /* ---- START SHIFT ---- */
        <div className="panel" style={{ maxWidth: 480 }}>
          <p className="panel-title">Start shift</p>
          <div className="disclaimer" style={{ marginBottom: 16 }}>
            Verify cartridge is fresh, not expired, and correctly installed before starting.
          </div>
          <form onSubmit={handleStart}>
            <div className="field">
              <label>Shift label</label>
              <select value={shiftLabel} onChange={(e) => setShiftLabel(e.target.value)}>
                <option>Morning Shift</option>
                <option>Afternoon Shift</option>
                <option>Night Shift</option>
              </select>
            </div>
            <div className="field">
              <label>Cartridge ID</label>
              <input
                value={cartridgeId}
                onChange={(e) => setCartridgeId(e.target.value)}
                placeholder="H2S-CART-001"
              />
            </div>
            <button className="btn btn-primary" disabled={busy}>
              {busy ? 'Starting…' : 'Start shift'}
            </button>
          </form>
          <p style={{ fontSize: 12, color: 'var(--text-faint)', marginTop: 14 }}>
            Demo cartridges: <span className="mono">H2S-CART-001</span>, <span className="mono">H2S-CART-002</span>
          </p>
        </div>
      ) : (
        /* ---- ACTIVE SHIFT ---- */
        <div className="stack">
          {/* Shift header */}
          <div className="panel shift-header-panel">
            <div>
              <div className="panel-title" style={{ marginBottom: 4 }}>Active shift</div>
              <div style={{ fontSize: 14 }}>
                {shift.shift_label} · started {new Date(shift.start_time).toLocaleTimeString()}
              </div>
            </div>
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
              <button className="btn-sos btn" onClick={handleSOS}>SOS</button>
              <button className="btn btn-danger" onClick={handleEnd} disabled={busy}>End shift</button>
            </div>
          </div>

          {/* Main readouts */}
          <div className="grid-3">
            <div className="panel">
              <Readout label="H₂S (electronic sensor)" value={latest?.h2s_ppm ?? '—'} unit="ppm" risk={risk} />
              <div style={{ marginTop: 10 }}><Badge level={risk} /></div>
            </div>
            <div className="panel">
              <Readout
                label="Est. cumulative exposure"
                value={cumulativeExposure}
                unit="ppm·hr"
                risk={cumulativeExposure >= 30 ? 'DANGER' : cumulativeExposure >= 10 ? 'WARNING' : 'NORMAL'}
              />
            </div>
            <div className="panel">
              <Readout label="Heart rate" value={latest?.hr_bpm ?? '—'} unit="bpm" risk="NORMAL" />
            </div>
          </div>

          <div className="grid-3">
            <div className="panel">
              <Readout label="SpO₂" value={latest?.spo2_pct ?? '—'} unit="%" risk="NORMAL" />
            </div>
            <div className="panel">
              <Readout label="Temperature" value={latest?.temp_c ?? '—'} unit="°C" risk="NORMAL" />
            </div>
            <div className="panel">
              <Readout
                label="Motion status"
                value={motionLabel(motionSt)}
                risk={motionRisk(motionSt)}
              />
            </div>
          </div>

          {/* Additional status row */}
          <div className="grid-3">
            <div className="panel">
              <div className="readout-label">Cartridge</div>
              <div style={{ marginTop: 6, fontSize: 14 }}>
                <span className="mono">{cartridgeId}</span>
                <div style={{ marginTop: 4 }}><Badge level="NORMAL" /></div>
              </div>
            </div>
            <div className="panel">
              <div className="readout-label">Worker</div>
              <div style={{ marginTop: 6, fontSize: 14 }}>
                <span className="mono">{session.workerId}</span>
                <div style={{ color: 'var(--text-dim)', fontSize: 12, marginTop: 2 }}>{session.name}</div>
              </div>
            </div>
            <div className="panel">
              <div className="readout-label">Battery (simulated)</div>
              <div style={{ marginTop: 6 }}>
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 28, fontWeight: 500 }}>87</span>
                <span className="readout-unit">%</span>
              </div>
            </div>
          </div>

          {/* H₂S trend chart */}
          {chartData.length > 1 && (
            <div className="panel">
              <p className="panel-title">H₂S concentration trend</p>
              <div style={{ width: '100%', height: 220 }}>
                <ResponsiveContainer>
                  <LineChart data={chartData} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
                    <XAxis
                      dataKey="time"
                      stroke="var(--text-faint)"
                      tick={{ fontSize: 10 }}
                      interval="preserveStartEnd"
                    />
                    <YAxis stroke="var(--text-faint)" tick={{ fontSize: 10 }} />
                    <Tooltip
                      contentStyle={{
                        background: 'var(--panel)',
                        border: '1px solid var(--grid)',
                        borderRadius: 4,
                        fontSize: 12,
                      }}
                    />
                    <ReferenceLine y={10} stroke="var(--amber)" strokeDasharray="4 4" label={{ value: 'WARN', fill: 'var(--amber)', fontSize: 10 }} />
                    <ReferenceLine y={20} stroke="var(--red)" strokeDasharray="4 4" label={{ value: 'DANGER', fill: 'var(--red)', fontSize: 10 }} />
                    <Line type="monotone" dataKey="h2s" stroke="var(--blue)" strokeWidth={2} dot={false} name="H₂S ppm" />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}

          {/* Simulation controls */}
          <div className="panel sim-controls">
            <p className="panel-title">Simulation controls</p>
            <p style={{ fontSize: 12, color: 'var(--text-faint)', marginBottom: 12 }}>
              Adjust simulated sensor readings for demonstration purposes.
            </p>
            <div className="sim-btn-group">
              <span style={{ fontSize: 11, color: 'var(--text-faint)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                H₂S Level:
              </span>
              {['normal', 'warning', 'danger', 'emergency'].map((level) => (
                <button
                  key={level}
                  className={`btn sim-btn ${sim.h2sLevel === level ? 'sim-btn-active' : ''}`}
                  onClick={() => setH2sLevel(level)}
                >
                  {level}
                </button>
              ))}
            </div>
            <div className="sim-btn-group">
              <span style={{ fontSize: 11, color: 'var(--text-faint)', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                Events:
              </span>
              <button
                className={`btn sim-btn ${motionSt === 'fall_suspected' ? 'sim-btn-active' : ''}`}
                onClick={() => setMotionState(motionSt === 'fall_suspected' ? 'normal' : 'fall_suspected')}
              >
                {motionSt === 'fall_suspected' ? '✓ Fall active' : 'Trigger fall'}
              </button>
              <button
                className={`btn sim-btn ${motionSt === 'inactive' ? 'sim-btn-active' : ''}`}
                onClick={() => setMotionState(motionSt === 'inactive' ? 'normal' : 'inactive')}
              >
                {motionSt === 'inactive' ? '✓ Inactive' : 'Trigger inactivity'}
              </button>
              <button className="btn sim-btn" onClick={fireSOS}>
                Trigger SOS
              </button>
            </div>
          </div>

          {/* Live alerts */}
          <div className="panel">
            <p className="panel-title">Live alerts</p>
            <AlertFeed alerts={alerts} />
          </div>

          <div className="disclaimer">
            Live readings are simulated in the browser for this prototype (no physical ESP32 connected).
            The same <span className="mono">POST /api/sensors/&#123;shift_id&#125;/reading</span> endpoint
            accepts real BLE/Wi-Fi packets from the wearable firmware once hardware is available.
            Biometric data (HR, SpO₂) are supporting safety indicators only and do not constitute medical diagnosis.
          </div>
        </div>
      )}
    </div>
  );
}
